- 
  version: '{build}'
  branches:
    except:
    - master
  skip_tags: true
  image: Visual Studio 2017
  before_build:
    - cmd: dotnet restore
  build:
    verbosity: normal
  artifacts:
  - path: '**\HotFix*.nupkg'
    name: Nuget packages
- 
  version: 0.4.0.{build}
  branches:
    only:
    - master
  skip_tags: true
  configuration: Release
  image: Visual Studio 2017
  dotnet_csproj:
    patch: true
    file: '**\*.csproj'
    version: '{version}'
    package_version: '{version}'
    assembly_version: '{version}'
    file_version: '{version}'
  before_build:
    - cmd: dotnet restore
  build:
    verbosity: minimal
  artifacts:
  - path: '**\HotFix*.nupkg'
    name: Nuget packages
