FROM microsoft/dotnet:2.1-runtime-deps-stretch-slim-arm32v7 AS base

FROM microsoft/dotnet:2.1-sdk-alpine AS builder
ENV NUGET_XMLDOC_MODE skip
COPY . /src
RUN dotnet publish -c Release -r linux-arm -o /app /src/HotFix.Demo.Initiator/HotFix.Demo.Initiator.csproj

FROM base AS production
COPY --from=builder /app /app

ENTRYPOINT ["/app/HotFix.Demo.Initiator"]
CMD ["127.0.0.1", "12345", "10000"]